dist: trusty
language: go
go_import_path: github.com/coreos/etcd
sudo: false

go:
  - 1.5
  - 1.6
  - tip

env:
  global:
   - GO15VENDOREXPERIMENT=1
  matrix:
   - TARGET=amd64
   - TARGET=arm64

matrix:
  allow_failures:
    - go: tip

addons:
  apt:
    packages:
    - libpcap-dev
    - libaspell-dev
    - libhunspell-dev

before_install:
 - go get -v github.com/chzchzchz/goword
 - go get -v honnef.co/go/simple/cmd/gosimple
 - go get -v honnef.co/go/unused/cmd/unused

# disable godep restore override
install:
 - pushd cmd/ && go get -t -v ./... && popd

script:
 - >
        if [ "${TARGET}" == "amd64" ]; then
                 GOARCH="${TARGET}" ./test;
        elif [ "${TARGET}" == "arm64" ]; then
                GOARCH="${TARGET}" ./build;
        fi
